### ISSUE TITLE
`swap_endian_impl` macro fails on Aarch64

### ISSUE THREAD

**Issue by thisjaiden** [TheAIguy-dev/ussr#1]
When building on an Aarch64 target, an error chain occurs when trying to compile the macro in `ussr-nbt/src/swap-endian`.
The compiler reports:
```
error: the feature named `avx2` is not valid for this target
  --> ussr-nbt/src/swap_endian.rs:11:34
   |
11 |                    #[target_feature(enable = $feature)]
   |  ___________________________________^
12 | |                  unsafe fn [<swap_endian_ $name>]<T: Num>(s: &mut [T]) {
13 | |                      for i in s.iter_mut() {
14 | |                          *i = i.swap_bytes();
...  |
34 | |/ swap_endian_impl! {
35 | ||     avx2: "avx2",
   | ||________________^ `avx2` is not valid for this target
36 |  |     avx: "avx",
37 |  |     sse4_2: "sse4.2",
...   |
42 |  |     sse: "sse",
43 |  | }
   |  |_- in this macro invocation
```
once for every pair inside of `swap_endian_impl! { ... }`, giving 8 errors.

Rust macros scare me deeply. I am happy to provide any needed information or tests, but I have no idea what's really happening here. As far as I can tell this should work, as it's just allowing a faster impl if available on the hardware, right?

**Comment by TheAIguy-dev** [comment]
Apparently the `#[target_feature]` attribute only works with features that are available on the current target. I'll put them behind `#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]` and it should be fixed.

**Comment by TheAIguy-dev** [comment]
Also, hey, it's you, the creator of golden apple! Nice to see you here :)

**Comment by thisjaiden** [comment]
Haha, thanks, thought I'd double check my work against your benchmarks and this is a cool project. I'll note that I'm still getting the same issue even after the fix, since `ussr-protocol` has an [old version](https://github.com/TheAIguy-dev/ussr/blob/5423fef586b54ac03cf3228a618b93eea0ca79a1/ussr-protocol/Cargo.toml#L14) of `ussr-nbt`

**Comment by TheAIguy-dev** [comment]
Yup, I upgraded all dependecies, now it should work
